function [fitresult, gof] = fitSimpleExp(d, I_mean2)
%CREATEFIT(D,I_MEAN2)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : d
%      Y Output: I_mean2
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 09-Oct-2014 16:20:57


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( d, I_mean2 );

% Set up fittype and options.
ft = fittype( 'exp(-b*x)+c', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf];
%opts.StartPoint = [0.288598149495284 0.687858027064559];
opts.Upper = [Inf Inf];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% % Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'I_mean2 vs. d', 'untitled fit 1', 'Location', 'NorthEast' );
% % Label axes
% xlabel( 'd' );
% ylabel( 'I_mean2' );
% grid on


